tree_list = [{'eng': 'European red pine', 'latin': 'Pinus sylvestris', 'pic': 'tall.jpg'},
             {'eng': 'Norway spruce', 'latin': 'Picea abies', 'pic': 'gran.jpg'},
             {'eng': 'European beech', 'latin': 'Fagus sylvatica', 'pic': 'bok.jpg'},
             {'eng': 'Grand Fir', 'latin': 'Abies grandis'},
             {'eng': 'Field Maple', 'latin': 'Acer campestre'},
             {'eng': 'Norway Maple', 'latin': 'Acer platanoides'},
             {'eng': 'Sycamore Maple', 'latin': 'Acer pseudoplatanus'},
             {'eng': 'Sugar Maple', 'latin': 'Acer saccharum'},
             {'eng': 'Horse Chestnut', 'latin': 'Aesculus hippocastanum'},
             {'eng': 'Common Alder', 'latin': 'Alnus glutinosa'},
             {'eng': 'Grey Alder', 'latin': 'Alnus incana'},
             {'eng': 'Silver Birch', 'latin': 'Betula pendula'},
             {'eng': 'Downy Birch', 'latin': 'Betula pubescens'},
             {'eng': 'Common Hornbeam', 'latin': 'Carpinus betulus'},
             {'eng': 'Cornelian Cherry', 'latin': 'Cornus mas'},
             {'eng': 'Common Dogwood', 'latin': 'Cornus sanguinea'},
             {'eng': 'Common Hazel', 'latin': 'Corylus avellana'},
             {'eng': 'Common Hawthorn', 'latin': 'Crataegus monogyna'},
             {'eng': 'Common Beech', 'latin': 'Fagus sylvatica'},
             {'eng': 'Common Ash', 'latin': 'Fraxinus excelsior'},
             {'eng': 'Maidenhair Tree', 'latin': 'Ginkgo biloba'},
             {'eng': 'Common Walnut', 'latin': 'Juglans regia'},
             {'eng': 'Common Juniper', 'latin': 'Juniperus communis'},
             {'eng': 'European Larch', 'latin': 'Larix decidua'},
             {'eng': 'Japanese Larch', 'latin': 'Larix kaempferi'},
             {'eng': 'Wild Crab', 'latin': 'Malus sylvestris'},
             {'eng': 'Norway Spruce', 'latin': 'Picea abies'},
             {'eng': 'Sitka Spruce', 'latin': 'Picea sitchensis'},
             {'eng': 'Lodgepole Pine', 'latin': 'Pinus contorta'},
             {'eng': 'Mountain Pine', 'latin': 'Pinus mugo'},
             {'eng': 'Austrian Pine', 'latin': 'Pinus nigra'},
             {'eng': 'Ponderosa Pine', 'latin': 'Pinus ponderosa'},
             {'eng': 'Weymouth Pine', 'latin': 'Pinus strobus'},
             {'eng': 'Scots Pine', 'latin': 'Pinus sylvestris'},
             {'eng': 'Wild Cherry', 'latin': 'Prunus avium'},
             {'eng': 'Bird Cherry', 'latin': 'Prunus padus'},
             {'eng': 'Douglas Fir', 'latin': 'Pseudotsuga menziesii'},
             {'eng': 'Common Pear', 'latin': 'Pyrus communis'},
             {'eng': 'Sessile Oak', 'latin': 'Quercus petraea'},
             {'eng': 'English Oak', 'latin': 'Quercus robur'},
             {'eng': 'Red Oak', 'latin': 'Quercus rubra'},
             {'eng': 'Goat Willow', 'latin': 'Salix caprea'},
             {'eng': 'European Elder', 'latin': 'Sambucus nigra'},
             {'eng': 'Common Rowan', 'latin': 'Sorbus aucuparia'},
             {'eng': 'Swedish Whitebeam', 'latin': 'Sorbus intermedia'},
             {'eng': 'Common Yew', 'latin': 'Taxus baccata'},
             {'eng': 'Small-leaved Lime', 'latin': 'Tilia cordata'},
             {'eng': 'Broad-leaved Lime', 'latin': 'Tilia platyphyllos'},
             {'eng': 'Eastern Hemlock', 'latin': 'Tsuga canadensis'},
             {'eng': 'Wynch Elm', 'latin': 'Ulmus glabra'},
             {'latin': 'Tilia × europaea', 'eng': 'Common Lime'},
             {'latin': 'Platanus × hispanica', 'eng': 'London Plane'},
             {'latin': ' Populus × canadensis \'Robusta\'', 'eng': 'Canadian Poplar'},
             {'eng': 'Hybrid Aspen', 'latin': ' Populus × wettsteinii'},
             {'eng': 'Aspen', 'latin': 'Populus tremula'},
             {'eng': 'Dunkeld Larch', 'latin': 'Larix x marschlinsii (eurolepis)'},
             {'eng': 'European Fly Honeysuckle', 'latin': 'Lonicera xylosteum'},
             {'eng': 'Blackthorn', 'latin': 'Prunus spinosa'},
             {'eng': 'Mountain Currant, Alpine Currant', 'latin': 'Ribes alpinum'},
             {'eng': 'White Willow', 'latin': 'Salix alba var. Sericea'},
             {'eng': 'European Red Elder', 'latin': 'Sambucus racemosa'},
             {'eng': 'Eastern White Cedar', 'latin': 'Thuja occidentalis'},
             {'eng': 'Western Red Cedar', 'latin': 'Thuja plicata'},
             {'eng': 'Guelder Rose', 'latin': 'Viburnum opulus'}]

newlist = sorted(tree_list, key=lambda d: d['eng'])
for a in newlist:
    print(str(a) + ',')