import os

list = [{'eng': 'Aspen', 'latin': 'Populus tremula'},
{'eng': 'Austrian Pine', 'latin': 'Pinus nigra'},
{'eng': 'Bird Cherry', 'latin': 'Prunus padus'},
{'eng': 'Blackthorn', 'latin': 'Prunus spinosa'},
{'eng': 'Broad-leaved Lime', 'latin': 'Tilia platyphyllos'},
{'latin': " Populus x canadensis 'Robusta'", 'eng': 'Canadian Poplar'},
{'eng': 'Common Alder', 'latin': 'Alnus glutinosa'},
{'eng': 'Common Ash', 'latin': 'Fraxinus excelsior'},
{'eng': 'Common Beech', 'latin': 'Fagus sylvatica'},
{'eng': 'Common Dogwood', 'latin': 'Cornus sanguinea'},
{'eng': 'Common Hawthorn', 'latin': 'Crataegus monogyna'},
{'eng': 'Common Hazel', 'latin': 'Corylus avellana'},
{'eng': 'Common Hornbeam', 'latin': 'Carpinus betulus'},
{'eng': 'Common Juniper', 'latin': 'Juniperus communis'},
{'latin': 'Tilia x europaea', 'eng': 'Common Lime'},
{'eng': 'Common Pear', 'latin': 'Pyrus communis'},
{'eng': 'Common Rowan', 'latin': 'Sorbus aucuparia'},
{'eng': 'Common Walnut', 'latin': 'Juglans regia'},
{'eng': 'Common Yew', 'latin': 'Taxus baccata'},
{'eng': 'Cornelian Cherry', 'latin': 'Cornus mas'},
{'eng': 'Douglas Fir', 'latin': 'Pseudotsuga menziesii'},
{'eng': 'Downy Birch', 'latin': 'Betula pubescens'},
{'eng': 'Dunkeld Larch', 'latin': 'Larix x marschlinsii (eurolepis)'},
{'eng': 'Eastern Hemlock', 'latin': 'Tsuga canadensis'},
{'eng': 'Eastern White Cedar', 'latin': 'Thuja occidentalis'},
{'eng': 'English Oak', 'latin': 'Quercus robur'},
{'eng': 'European Elder', 'latin': 'Sambucus nigra'},
{'eng': 'European Fly Honeysuckle', 'latin': 'Lonicera xylosteum'},
{'eng': 'European Larch', 'latin': 'Larix decidua'},
{'eng': 'European Red Elder', 'latin': 'Sambucus racemosa'},
{'eng': 'European beech', 'latin': 'Fagus sylvatica', 'pic': 'bok.jpg'},
{'eng': 'European red pine', 'latin': 'Pinus sylvestris', 'pic': 'tall.jpg'},
{'eng': 'Field Maple', 'latin': 'Acer campestre'},
{'eng': 'Goat Willow', 'latin': 'Salix caprea'},
{'eng': 'Grand Fir', 'latin': 'Abies grandis'},
{'eng': 'Grey Alder', 'latin': 'Alnus incana'},
{'eng': 'Guelder Rose', 'latin': 'Viburnum opulus'},
{'eng': 'Horse Chestnut', 'latin': 'Aesculus hippocastanum'},
{'eng': 'Hybrid Aspen', 'latin': ' Populus x wettsteinii'},
{'eng': 'Japanese Larch', 'latin': 'Larix kaempferi'},
{'eng': 'Lodgepole Pine', 'latin': 'Pinus contorta'},
{'eng': 'London Plane', 'latin': 'Platanus x hispanica'},
{'eng': 'Maidenhair Tree', 'latin': 'Ginkgo biloba'},
{'eng': 'Mountain Currant, Alpine Currant', 'latin': 'Ribes alpinum'},
{'eng': 'Mountain Pine', 'latin': 'Pinus mugo'},
{'eng': 'Norway Maple', 'latin': 'Acer platanoides'},
{'eng': 'Norway Spruce', 'latin': 'Picea abies'},
{'eng': 'Norway spruce', 'latin': 'Picea abies', 'pic': 'gran.jpg'},
{'eng': 'Ponderosa Pine', 'latin': 'Pinus ponderosa'},
{'eng': 'Red Oak', 'latin': 'Quercus rubra'},
{'eng': 'Scots Pine', 'latin': 'Pinus sylvestris'},
{'eng': 'Sessile Oak', 'latin': 'Quercus petraea'},
{'eng': 'Silver Birch', 'latin': 'Betula pendula'},
{'eng': 'Sitka Spruce', 'latin': 'Picea sitchensis'},
{'eng': 'Small-leaved Lime', 'latin': 'Tilia cordata'},
{'eng': 'Sugar Maple', 'latin': 'Acer saccharum'},
{'eng': 'Swedish Whitebeam', 'latin': 'Sorbus intermedia'},
{'eng': 'Sycamore Maple', 'latin': 'Acer pseudoplatanus'},
{'eng': 'Western Red Cedar', 'latin': 'Thuja plicata'},
{'eng': 'Weymouth Pine', 'latin': 'Pinus strobus'},
{'eng': 'White Willow', 'latin': 'Salix alba var. Sericea'},
{'eng': 'Wild Cherry', 'latin': 'Prunus avium'},
{'eng': 'Wild Crab', 'latin': 'Malus sylvestris'},
{'eng': 'Wynch Elm', 'latin': 'Ulmus glabra'}]

for a in list:
    if not os.path.isfile('../media/' + a['eng'] + '.jpg'):
        print(str(a) + ',')